---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.component }}-api-shared-data
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.component }}-api-maven-settings
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce